{{- if .Capabilities.APIVersions.Has "actions.github.com/v1alpha1" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "github-actions-runner.managerRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: arc-role-binding
  finalizers:
    - actions.github.com/cleanup-protection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "github-actions-runner.managerRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "github-actions-runner.managerServiceAccountName" . }}
  namespace: {{ default .Release.Namespace .Values.controllerServiceAccount.namespace }}
{{- end }}
