{{- if .Capabilities.APIVersions.Has "cert-manager.io/v1" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-issuer
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "github-actions-runner.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  secretName: {{ include "github-actions-runner.fullname" . }}-ca
  secretTemplate:
    labels:
      {{- include "github-actions-runner.labels" . | nindent 6 }}
  issuerRef:
    name: {{ include "github-actions-runner.fullname" . }}-issuer
    kind: Issuer
  commonName: {{ include "github-actions-runner.fullname" . }}
  duration: 26280h # 3y
  renewBefore: 26000h # ~3y
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
    - crl sign
  isCA: true
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-ca-issuer
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "github-actions-runner.fullname" . }}-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-server
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  secretName: {{ include "github-actions-runner.fullname" . }}-server-tls
  secretTemplate:
    labels:
      {{- include "github-actions-runner.labels" . | nindent 6 }}
  commonName: {{ include "github-actions-runner.fullname" . }}-server
  duration: 26280h # 3y
  renewBefore: 8760h # 1y
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - server auth
    - client auth
  isCA: false
  ipAddresses:
    - 127.0.0.1
  dnsNames:
    - {{ include "github-actions-runner.fullname" . }}
    - {{ include "github-actions-runner.fullname" . }}-mirrors.{{ .Release.Namespace }}.svc
    - {{ include "github-actions-runner.fullname" . }}-registry.{{ .Release.Namespace }}.svc
    {{- range $inx, $val := .Values.registry.ingress.hosts }}
    - {{ $val.host }}
    {{- end }}
  issuerRef:
    name: {{ include "github-actions-runner.fullname" . }}-ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-client
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
spec:
  secretName: {{ include "github-actions-runner.fullname" . }}-client-tls
  secretTemplate:
    labels:
      {{- include "github-actions-runner.labels" . | nindent 6 }}
  commonName: {{ include "github-actions-runner.fullname" . }}
  duration: 8760h # 1y
  renewBefore: 2190h # 3m
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - digital signature
    - client auth
  isCA: false
  ipAddresses:
    - 127.0.0.1
  dnsNames:
    - {{ include "github-actions-runner.fullname" . }}
  issuerRef:
    name: {{ include "github-actions-runner.fullname" . }}-ca-issuer
{{- else }}
---
{{- $ca := genCA (include "github-actions-runner.fullname" .) 3650 }}
{{- $host := printf "%s-mirrors" (include "github-actions-runner.fullname" .) }}
{{- $domain := printf "%s-mirrors.%s.svc" (include "github-actions-runner.fullname" .) .Release.Namespace }}
{{- $server := genSignedCert $host nil (list $host $domain) 3650 $ca }}
{{- $domainReg := printf "%s-registry.%s.svc" (include "github-actions-runner.fullname" .) .Release.Namespace }}
{{- $registry := genSignedCert $host nil (list $domainReg) 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-server-tls
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
type: Opaque
data:
{{- $serverName := printf "%s-server-tls" (include "github-actions-runner.fullname" .) }}
{{- $serverData := (lookup "v1" "Secret" .Release.Namespace $serverName).data }}
{{- if and $serverData (hasKey $serverData "ca.crt") }}
  ca.crt: {{ get $serverData "ca.crt" }}
  tls.crt: {{ get $serverData "tls.crt" }}
  tls.key: {{ get $serverData "tls.key" }}
{{- else }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $server.Cert | b64enc }}
  tls.key: {{ $server.Key | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-client-tls
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
type: Opaque
data:
{{- $clientName := printf "%s-client-tls" (include "github-actions-runner.fullname" .) }}
{{- $clientData := (lookup "v1" "Secret" .Release.Namespace $clientName).data }}
{{- if and $clientName (hasKey $clientData "ca.crt") }}
  ca.crt: {{ get $clientData "ca.crt" }}
  tls.crt: {{ get $clientData "tls.crt" }}
  tls.key: {{ get $clientData "tls.key" }}
{{- else }}
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $registry.Cert | b64enc }}
  tls.key: {{ $registry.Key | b64enc }}
{{- end }}
{{- end }}
