{{- if .Values.mirrors.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-actions-runner.mirrors.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
  {{- with .Values.mirrors.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
