{{- if .Values.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-actions-runner.fullname" . }}-proxy
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  annotations:
    service.kubernetes.io/topology-mode: Auto
spec:
  type: ClusterIP
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ipFamilyPolicy: {{ if eq (len .Values.service.ipFamilies) 2 }}PreferDualStack{{ else }}SingleStack{{ end }}
  ports:
    - name: http
      port: 3128
      targetPort: 3128
      protocol: TCP
  selector:
    {{- include "github-actions-runner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
{{- end }}
