{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-actions-runner.registry.fullname" . }}
  labels:
    {{- include "github-actions-runner.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "github-actions-runner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: registry
  template:
    metadata:
      annotations:
        checksum/config: {{ toJson .Values.registry.storage | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/scheme: https
        prometheus.io/port: "8443"
      labels:
        {{- include "github-actions-runner.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: registry
    spec:
      {{- if .Values.registry.serviceAccount.create }}
      serviceAccountName: {{ include "github-actions-runner.registry.serviceAccountName" . }}
      automountServiceAccountToken: true
      {{- else }}
      automountServiceAccountToken: false
      {{- end }}
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        fsGroup: 65534
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: {{ include "github-actions-runner.registry.fullname" . }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop: ["ALL"]
            runAsUser: 65534
            runAsGroup: 65534
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: {{ .Values.registry.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
          startupProbe:
            httpGet:
              path: /v2/
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
            - name: config
              mountPath: /etc/zot
            - name: tls
              mountPath: /etc/registry-tls
          {{- if .Values.registry.extraVolumeMounts }}
            {{ toYaml .Values.registry.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.registry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.registry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "github-actions-runner.fullname" . }}
            items:
              - key: registry.json
                path: config.json
        - name: tls
          secret:
            secretName:  {{ include "github-actions-runner.fullname" . }}-server-tls
            defaultMode: 256
        - name: data
      {{- if not .Values.registry.persistence.enabled }}
          emptyDir: {}
      {{- else }}
          ephemeral:
            volumeClaimTemplate:
              metadata:
                {{- with .Values.registry.persistence.annotations }}
                annotations:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
                labels:
                  {{- include "github-actions-runner.selectorLabels" . | nindent 18 }}
                  app.kubernetes.io/component: registry
              {{- include "volumeClaimTemplate.spec.render" .Values.registry.persistence | nindent 14 }}
      {{- end }}
      {{- if .Values.registry.extraVolumes }}
        {{ toYaml .Values.registry.extraVolumes | nindent 8 }}
      {{- end }}
{{- end }}
