{{- if .Values.ingressClassResource.enabled -}}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    {{- include "skipper.labels" . | nindent 4 }}
  name: {{ .Values.ingressClass }}
spec:
  controller: {{ .Values.ingressClassResource.controllerValue }}
{{- end }}
