{{- $sname := include "plausible.fullname" . }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace $sname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sname }}
  labels:
    {{- include "plausible.labels" . | nindent 4 }}
type: Opaque
data:
{{- if and $previous $previous.data $previous.data.SECRET_KEY_BASE }}
  SECRET_KEY_BASE: {{ $previous.data.SECRET_KEY_BASE | quote }}
{{- else }}
  SECRET_KEY_BASE: {{ default (randAlphaNum 48 | b64enc) .Values.config.secretKeyBase | b64enc | quote }}
{{- end }}
  TOTP_VAULT_KEY: {{ default (randAlphaNum 32 | b64enc) .Values.config.totpVaultKey | b64enc | quote }}
{{- range $name, $value := .Values.envs }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
