backend-common: [charts/backend-common/**]
bitwarden: [charts/bitwarden/**]
clickhouse-keeper: [charts/clickhouse-keeper/**]
clickhouse: [charts/clickhouse/**]
fluentd: [charts/fluentd/**]
github-actions-runner: [charts/github-actions-runner/**]
ipsec: [charts/ipsec/**]
keydb: [charts/keydb/**]
link-common: [charts/link-common/**]
mongodb-backup: [charts/mongodb-backup/**]
mongosqld: [charts/mongosqld/**]
mongosync: [charts/mongosync/**]
openvpn: [charts/openvpn/**]
overprovisioner: [charts/overprovisioner/**]
pgbouncer: [charts/pgbouncer/**]
plausible: [charts/plausible/**]
postgresql-single: [charts/postgresql-single/**]
prometheus-rules: [charts/prometheus-rules/**]
rbac-common: [charts/rbac-common/**]
registry-mirrors: [charts/registry-mirrors/**]
service-common: [charts/service-common/**]
skipper: [charts/skipper/**]
system-upgrade-controller: [charts/system-upgrade-controller/**]
tabix: [charts/tabix/**]
tailscale: [charts/tailscale/**]
teamcity: [charts/teamcity/**]
