apiVersion: v1
kind: Service
metadata:
  name: {{ include "openvpn.fullname" . }}
  labels:
    {{- include "openvpn.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  sessionAffinity: ClientIP
  type: {{ .Values.service.type }}
{{- if eq .Values.service.type "NodePort" }}
  externalTrafficPolicy: Local
{{- end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ipFamilyPolicy: {{ if eq (len .Values.service.ipFamilies) 2 }}PreferDualStack{{ else }}SingleStack{{ end }}
  ports:
    {{- range (eq .Values.service.proto "All" | ternary (list "tcp" "udp") (list .Values.service.proto)) }}
    - port: {{ $.Values.service.port }}
      targetPort: openvpn-{{ . }}
      protocol: {{ . | upper }}
      name: openvpn-{{ . }}
      {{- if eq "NodePort" $.Values.service.type }}
      nodePort: {{ default "30190" $.Values.service.nodePort }}
      {{- end }}
    {{- end }}
{{- with .Values.service.externalIPs  }}
  externalIPs:
{{ toYaml . | indent 4 }}
{{- end }}
  selector:
    {{- include "openvpn.selectorLabels" . | nindent 4 }}
