---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "system-upgrade-controller.fullname" . }}:drainer
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "system-upgrade-controller.fullname" . }}-drainer
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "system-upgrade-controller.fullname" . }}
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "system-upgrade-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  {{ include "system-upgrade-controller.fullname" . }}:upgrade
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "system-upgrade-controller.fullname" . }}-upgrade
subjects:
- kind: ServiceAccount
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
