{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ include "system-upgrade-controller.serviceAccountName" . }}-talos
  labels:
    {{- include "system-upgrade-controller.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  roles:
    - os:admin
{{- end }}
