apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
data:
  keeper-config.xml: |
    <clickhouse>
        <display_name>{{ include "clickhouse-keeper.fullname" . }}</display_name>
        <listen_host>0.0.0.0</listen_host>
        <listen_host>::</listen_host>
        <listen_try>1</listen_try>

        <logger>
            <level>information</level>
            <console>false</console>
            <size>1000M</size>
            <count>2</count>
            <log>/var/log/clickhouse/clickhouse-keeper.log</log>
            <errorlog>/var/log/clickhouse/clickhouse-keeper.err.log</errorlog>
        </logger>

        <keeper_server>
            <path>/var/lib/clickhouse-keeper</path>
            <tcp_port>2181</tcp_port>
            <four_letter_word_white_list>*</four_letter_word_white_list>
            <coordination_settings>
                <raft_logs_level>information</raft_logs_level>
            </coordination_settings>

            <server_id>0</server_id>
            <raft_configuration>
                <server>
                    <id>0</id>
                    <hostname>{{ include "clickhouse-keeper.fullname" . }}-0</hostname>
                    <port>9444</port>
                </server>
            </raft_configuration>
        </keeper_server>
    </clickhouse>
