apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "clickhouse-keeper.fullname" . }}
  labels:
    {{- include "clickhouse-keeper.labels" . | nindent 4 }}
    {{- with .Values.podlabels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  serviceName: {{ include "clickhouse-keeper.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
  selector:
    matchLabels:
      {{- include "clickhouse-keeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "7000"
      {{- end}}
      labels:
        {{- include "clickhouse-keeper.selectorLabels" . | nindent 8 }}
        {{- with .Values.podlabels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: false
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "clickhouse-keeper.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      containers:
        - name: {{ include "clickhouse-keeper.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - clickhouse-keeper
            - --config-file=/etc/clickhouse-keeper/keeper-config.xml
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          volumeMounts:
            - name: config
              mountPath: /etc/clickhouse-keeper
            - name: logs
              mountPath: /var/log/clickhouse
            - name: data
              mountPath: /var/lib/clickhouse-keeper
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "clickhouse-keeper.fullname" . }}
        - name: logs
          emptyDir: {}
        - name: data
          emptyDir: {}
