apiVersion: v2
name: openvpn
description: OpenVPN in kubernetes
type: application
home: https://github.com/sergelogvinov/helm-charts
sources:
- https://github.com/sergelogvinov/helm-charts/tree/master/charts/openvpn
- https://openvpn.net
keywords:
- openvpn
maintainers:
- name: sergelogvinov
  url: https://github.com/sergelogvinov

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.4.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.6.8"
