{{- if .Values.service.port }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tailscale.fullname" . }}-p2p
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: None
  externalTrafficPolicy: Local
  ipFamilyPolicy: {{ if eq (len .Values.service.ipFamilies) 2 }}PreferDualStack{{ else }}SingleStack{{ end }}
  {{- with .Values.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.port }}
      targetPort: p2p
      protocol: UDP
      name: p2p
  selector:
    {{- include "tailscale.selectorLabels" . | nindent 4 }}
{{- end }}
