# Default values for bitwarden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

envs:
  # -- smtp username
  SMTP_USERNAME: 'username'
  # -- smtp password
  SMTP_PASSWORD: 'password'
  # -- Admin token,
  # use `/vaultwarden hash` to encrypt password
  ADMIN_TOKEN: 'token'
  # -- After creation, better to disable admin portal
  DISABLE_ADMIN_TOKEN: 'false'

# -- Official documentation
# https://github.com/dani-garcia/vaultwarden/wiki/Configuration-overview
config:
  SMTP_HOST: 'smtp.domain.tld'
  SMTP_FROM: 'bitwarden-rs@domain.tld'
  SMTP_FROM_NAME: 'Vault'
  SMTP_PORT: 587
  SMTP_SECURITY: starttls
  #
  WEB_VAULT_ENABLED: true
  ROCKET_WORKERS: 10
  #
  EXTENDED_LOGGING: true
  ROCKET_CLI_COLORS: 'off'
  #
  SIGNUPS_ALLOWED: false
  SIGNUPS_VERIFY: false
  SIGNUPS_DOMAINS_WHITELIST: 'domain.tld'
  INVITATIONS_ALLOWED: true
  INVITATION_ORG_NAME: 'Bitwarden'
  SHOW_PASSWORD_HINT: false
  #
  USER_ATTACHMENT_LIMIT: 1048576
  ORG_ATTACHMENT_LIMIT: 1048576

# -- Pods Service Account.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for pod.
# ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}

# -- Pod Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 33
  runAsGroup: 33
  fsGroup: 33
  fsGroupChangePolicy: "OnRootMismatch"

# -- Container Security Context.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
securityContext:
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
  runAsUser: 33
  runAsGroup: 33
  # readOnlyRootFilesystem: true

# -- Bitwarden service parameters
# ref: https://kubernetes.io/docs/user-guide/services/
service:
  # -- service type
  type: ClusterIP
  # -- service port
  port: 80
  # -- websocket service port
  portWSocket: 3012

  ipFamilies: [IPv4]

# -- Bitwarden ingress parameters
# ref: http://kubernetes.io/docs/user-guide/ingress/
ingress:
  enabled: false
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/limit-connections: "25"
    nginx.ingress.kubernetes.io/limit-rps: "15"
  hosts:
    - host: vault.local

  tls: []
  #  - secretName: vault.local-tls
  #    hosts:
  #      - vault.local

# -- Resource requests and limits.
# ref: https://kubernetes.io/docs/user-guide/compute-resources/
resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# -- Persistence parameters
# ref: https://kubernetes.io/docs/user-guide/persistent-volumes/
persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # storageClass: "-"
  accessModes: [ReadWriteOnce]
  size: 10Gi
  annotations: {}

# -- Controller deployment update strategy type.
# ref: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

# -- Node labels for controller assignment.
# ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

# -- Tolerations for controller assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

# -- Affinity for controller assignment.
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}
