{{- if and (not .Values.configConfigMap) .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-common.fullname" . }}
  labels:
    {{- include "backend-common.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: |-
{{ $value | indent 4 }}
{{- end }}
{{- end }}
