{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-common.fullname" . }}
  labels:
    {{- include "backend-common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
{{- if ne (len .Values.envSecrets) 0 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-common.fullname" . }}-env
  labels:
    {{- include "backend-common.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.envSecrets }}
  {{ $name }}: {{ tpl $value $ | b64enc | quote }}
{{- end }}
{{- end }}
